
FIND_PAcKAGE(CMLIB COMPONENTS CMUTIL REQUIRED)

SET(STORAGE_LIST TESTLIB)

# Define URI for TESTLIB storage. We can use CMLIB ENV variables
CMUTIL_NORMALIZE_GIT_URI(
    URI        "${CMLIB_REQUIRED_ENV_REMOTE_URL}/cmakelib-test.git"
    OUTPUT_VAR STORAGE_LIST_TESTLIB
)
